using Application.Client.Windows.ApplicationWindow.ViewModels.ApplicationWindowSettings;
using Application.Client.Windows.DialogWindow.ViewModels.DialogWindowSettings.Interfaces;

namespace Application.Client.Windows.DialogWindow.ViewModels.DialogWindowSettings;

public class DialogWindowSettingsViewModel : ApplicationWindowSettingsViewModel, IDialogWindowSettingsViewModel
{ }