using Application.Client.Windows.DialogWindow.ViewModels.DialogWindow.Initializers.Models;
using Application.Client.Windows.Implementations.ExceptionDialog.Window.ViewModels.ExceptionDialogWindowSettings.Initializer.Models;

namespace Application.Client.Windows.Implementations.ExceptionDialog.Window.ViewModels.ExceptionDialogWindow.Initializer.Models;

public class ExceptionDialogWindowViewModelInitializerModel : DialogWindowViewModelInitializerModel<ExceptionDialogWindowSettingsViewModelInitializerModel>
{ }