using Application.Client.Windows.Core.ViewModels.WindowSettings.Initializer.Models.Interfaces;

namespace Application.Client.Windows.NavigationWindow.ViewModels.NavigationWindowSettings.Initializers.Models.Interfaces;

public interface INavigationWindowSettingsViewModelInitializerModel : IWindowSettingsViewModelInitializerModel
{ }