using Application.Client.Windows.DialogWindow.ViewModels.DialogWindow.Initializers.Models;
using Application.Client.Windows.Implementations.MessageBox.Window.ViewModels.MessageBoxWindowSettings.Initializer.Models;

namespace Application.Client.Windows.Implementations.MessageBox.Window.ViewModels.MessageBoxWindow.Initializer.Models;

public class MessageBoxWindowViewModelInitializerModel : DialogWindowViewModelInitializerModel<MessageBoxWindowSettingsViewModelInitializerModel>
{ }