using Application.Client.Windows.Core.ViewModels.WindowSettings.Initializer.Models;
using Application.Client.Windows.DialogWindow.Core.ViewModels.DialogWindowSettings.Initializers.Models.Interfaces;

namespace Application.Client.Windows.DialogWindow.Core.ViewModels.DialogWindowSettings.Initializers.Models;

public class DialogWindowSettingsViewModelInitializerModel : WindowSettingsViewModelInitializerModel, IDialogWindowSettingsViewModelInitializerModel
{ }