using Application.Client.Windows.Core.ViewModels.WindowSettings.Initializer.Models;
using Application.Client.Windows.NavigationWindow.Core.ViewModels.NavigationWindowSettings.Initializers.Models.Interfaces;

namespace Application.Client.Windows.NavigationWindow.Core.ViewModels.NavigationWindowSettings.Initializers.Models;

public class NavigationWindowSettingsViewModelInitializerModel : WindowSettingsViewModelInitializerModel, INavigationWindowSettingsViewModelInitializerModel
{ }