using Application.Client.Windows.DialogWindow.ViewModels.DialogWindowSettings.Initializers.Models;

namespace Application.Client.Windows.Implementations.MessageDialog.Window.ViewModels.MessageDialogWindowSettings.Initializer.Models;

public class MessageDialogWindowSettingsViewModelInitializerModel : DialogWindowSettingsViewModelInitializerModel
{ }