using Application.Client.Windows.NavigationWindow.ViewModels.NavigationWindow.Initializers.Models;

namespace Application.Client.Windows.Implementations.Main.Window.ViewModels.MainWindow.Initializer.Models;

public class MainWindowViewModelInitializerModel : NavigationWindowViewModelInitializerModel<MainWindowSettingsViewModelInitializerModel>
{ }