namespace Application.Client.Windows.Navigation.ViewNavigation.Pages.ViewModelInitializers.PageViewModelInitializer.InitializerModels.Abstractions;

public abstract class PageViewDataViewModelInitializerModelBase
{ }