using Application.Client.Windows.ApplicationWindow.ViewModels.ApplicationWindowSettings;
using Application.Client.Windows.NavigationWindow.ViewModels.NavigationWindowSettings.Interfaces;

namespace Application.Client.Windows.NavigationWindow.ViewModels.NavigationWindowSettings;

public class NavigationWindowSettingsViewModel : ApplicationWindowSettingsViewModel, INavigationWindowSettingsViewModel
{ }