using Application.Client.Windows.Windows.ApplicationWindow.Interfaces;

namespace Application.Client.Windows.Windows.ApplicationWindow.ViewModels.Initializers.Interfaces;

public interface IApplicationWindowViewModelInitializer<in TApplicationWindowViewModel, in TApplicationWindowViewModelInitializerModel>
    where TApplicationWindowViewModel : IApplicationWindowViewModel
    where TApplicationWindowViewModelInitializerModel : IApplicationWindowViewModelInitializerModel
{
    public void Initialize(TApplicationWindowViewModel applicationWindowViewModel, TApplicationWindowViewModelInitializerModel applicationWindowViewModelInitializerModel);
}