using Application.Client.Windows.Windows.ApplicationWindow.ViewModels.Abstractions;
using Application.Client.Windows.Windows.ApplicationWindow.ViewModels.Initializers.Abstractions;

namespace Application.Client.Windows.Windows.ApplicationWindow.ViewModels.Initializers.Interfaces;

public interface IApplicationWindowViewModelInitializer<in TApplicationWindowViewModel, in TApplicationWindowViewModelInitializerModel>
    where TApplicationWindowViewModel : ApplicationWindowViewModelBase
    where TApplicationWindowViewModelInitializerModel : BaseApplicationWindowViewModelInitializerModel
{
    public void Initialize(TApplicationWindowViewModel applicationWindowViewModel, TApplicationWindowViewModelInitializerModel applicationWindowViewModelInitializerModel);
}