using Application.Client.Windows.NavigationWindow.ViewModels.NavigationWindowSettings.Initializers.Models;

namespace Application.Client.Windows.Implementations.Main.Window.ViewModels.MainWindowSettings.Initializer.Models;

public class MainWindowSettingsViewModelInitializerModel : NavigationWindowSettingsViewModelInitializerModel
{ }