using Application.Client.Windows.Windows.ApplicationWindow.ViewModels.Initializers.Abstractions;

namespace Application.Client.Windows.Navigation.ViewNavigation.Windows.NavigationWindow.ViewModels.Initializers.Abstractions.Models;

public abstract class BaseNavigationWindowSettingsViewModelInitializerModel : BaseApplicationWindowSettingsViewModelInitializerModel
{ }