using Application.Client.Windows.ApplicationWindow.ViewModels.ApplicationWindow.Initializers.Models.Interfaces;

namespace Application.Client.Windows.NavigationWindow.ViewModels.NavigationWindow.Initializers.Models.Interfaces;

public interface INavigationWindowViewModelInitializerModel : IApplicationWindowViewModelInitializerModel
{ }