using Application.Client.Windows.ApplicationWindow.ViewModels.ApplicationWindowSettings.Initializers.Models.Interfaces;
using Application.Client.Windows.Core.ViewModels.WindowSettings.Initializer.Models;

namespace Application.Client.Windows.ApplicationWindow.ViewModels.ApplicationWindowSettings.Initializers.Models;

public class ApplicationWindowSettingsViewModelInitializerModel : WindowSettingsViewModelInitializerModel, IApplicationWindowSettingsViewModelInitializerModel
{ }