using Application.Client.Windows.DialogWindow.Core.ViewModels.DialogWindowSettings.Initializers.Models;

namespace Application.Client.Windows.DialogWindow.Impl.ExceptionDialog.Window.ViewModels.ExceptionDialogWindowSettings.Initializer.Models;

public class ExceptionDialogWindowSettingsViewModelInitializerModel : DialogWindowSettingsViewModelInitializerModel
{ }