using Application.Client.Windows.DialogWindow.Core.ViewModels.DialogWindowSettings.Initializers.Models;

namespace Application.Client.Windows.DialogWindow.Impl.MessageBox.Window.ViewModels.MessageBoxWindowSettings.Initializer.Models;

public class MessageBoxWindowSettingsViewModelInitializerModel : DialogWindowSettingsViewModelInitializerModel
{ }