using Application.Client.Windows.Core.ViewModels.WindowSettings.Initializer.Models.Interfaces;

namespace Application.Client.Windows.ApplicationWindow.ViewModels.ApplicationWindowSettings.Initializers.Models.Interfaces;

public interface IApplicationWindowSettingsViewModelInitializerModel : IWindowSettingsViewModelInitializerModel
{ }