using Application.Client.Windows.ApplicationWindow.ViewModels.ApplicationWindowSettings.Interfaces;

namespace Application.Client.Windows.NavigationWindow.ViewModels.NavigationWindowSettings.Interfaces;

public interface INavigationWindowSettingsViewModel : IApplicationWindowSettingsViewModel
{ }