using Application.Client.Windows.ApplicationWindow.ViewModels.ApplicationWindow.Initializers.Models.Interfaces;
using Application.Client.Windows.ApplicationWindow.ViewModels.ApplicationWindow.Interfaces;

namespace Application.Client.Windows.ApplicationWindow.ViewModels.ApplicationWindow.Initializers.Interfaces;

public interface IApplicationWindowViewModelInitializer<in TApplicationWindowViewModel, in TApplicationWindowViewModelInitializerModel>
    where TApplicationWindowViewModel : IApplicationWindowViewModel
    where TApplicationWindowViewModelInitializerModel : IApplicationWindowViewModelInitializerModel
{
    public void Initialize(TApplicationWindowViewModel applicationWindowViewModel, TApplicationWindowViewModelInitializerModel applicationWindowViewModelInitializerModel);
}